name: cron check the sequel

on:
  schedule:
    - cron: '10 * * * *'
  push:
    branches:
      - master
jobs:
  top-of-the-hour-plus-5-minutes-to-you:

    runs-on: ubuntu-latest

    steps:
    - name: What time is it?
      run: |
        date
