name: CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: payload me
      run: cat $GITHUB_EVENT_PATH
    - name: github.ref
      run: |
        echo ${{ github.ref }}
