name: get the pull request number

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: print out the payload
      run: |
        cat $GITHUB_EVENT_PATH
    - name: extract the PR number from the payload and print it
      run: |
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo $pull_number
    - name: print the $GITHUB_REF
      run: |
        echo $GITHUB_REF
    - name: print github.ref
      run: |
        echo ${{ github.ref }}
    - name: print github.ref
      run: |
        echo ${{ github.ref }}
    - name: print github.event
      run: |
        echo ${{ toJson(event) }}
    - name: extract the PR number from the payload and print it
      run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "${{ github.event_path }}")
          echo $PR_NUMBER
